- app/index.html
- app/scripts/controllers/AppController.js
- app/scripts/keycloak-init.js
removing hard coded URLs, leveraging API
> :lipstick: changes

- app/scripts/keycloak-init.js
For Keycloak decoupling  - Do not merge
> WIP: Keycloak decoupling

- bower.json
> Keycloak 3.2.1 bundle

- app/components/bootstrap/bootstrap.html
- app/dialogs/create-variant.html
- app/styles/main.less
Remove ADM support. To be verified together with https://github.com/aerogear/aerogear-unifiedpush-server/pull/996 (putting the verification steps there)
> remove experimental adm support

- .bowerrc
- app/snippets/register-device/android.java
While upskilling I notice this bug
https://issues.jboss.org/browse/AEROGEAR-9055
Fixed sample code
To provide consumers code without bugs
Fix reference name to correct one
> Fix bug in android sample code

- app/snippets/senders/sender-nodejs.js
> Update UnifiedPush node sender api instruction

- app/styles/main.less
Fixes the webpush icon to be the chrome icon
> adding webpush

- app/styles/main.less
> adding ios token

- app/components/app-detail/include/variantDetail.html
- app/dialogs/create-variant.html
- app/directives/ups-client-snippets.html
- app/scripts/app.js
- app/scripts/directives.js
- app/scripts/services/pushConfigGenerator.js
- app/scripts/services/variantModal.js
- npm-shrinkwrap.json
This PR adds webpush to the admin ui
`mvn clean install`
then build `https://github.com/aerogear/aerogear-unifiedpush-server/pull/1050`
run UPS
then create a web push variant in the UI
> adding webpush ui

- app/components/app-detail/include/variantDetail.html
- app/dialogs/create-variant.html
- app/scripts/app.js
- app/scripts/directives.js
- app/scripts/services/pushConfigGenerator.js
- app/scripts/services/variantModal.js
- npm-shrinkwrap.json
- package.json
This adds APNS Token Variant creation/editing to UPS
> apns token ui

- app/index.html
- app/scripts/config-init.js
- app/scripts/controllers/AppController.js
- app/scripts/controllers/IdleController.js
- assets.js
- package-lock.json
- package.json
Keycloak integration was broken in the latest UI
Refactoring to add the configurable UI broke the keycloak login flow.  Since we usuallyu use oauth proxy this wasn't noticed in production.
* Build this PR 
* Build https://github.com/secondsun/aerogear-unifiedpush-server/tree/fix_keycloak which will include this build
* Run UPS using docker compose and verify keycloak still works. (This may be difficult because of OS networking differences.  It works on linux)
> Fixing keycloak breaks

- .github/workflows/build.yml
- package-lock.json
- package.json
- src/App.tsx
- src/common/Header.tsx
- src/landing/Welcome.tsx
- src/wizard/ActionBox.tsx
- src/wizard/WizardStep1.tsx
> Added CI/CD

- package-lock.json
- package.json
- src/App.tsx
- src/application/ApplicationHome.tsx
- src/landing/Welcome.tsx
More minor edits, note that you will need to edit the call to the client in App.tsx as well as disable cors to demo this PR
> Splitting Wizard and Applications in Welcome

- package.json
- src/application/ApplicationDetail/ApplicationDetail.tsx
- src/application/ApplicationList/ApplicationList.tsx
- src/application/ApplicationList/ApplicationListItem.tsx
- src/application/crud/CreateApplicationPage.tsx
- src/application/crud/DeleteApplicationPage.tsx
- src/application/crud/UpdateApplicationPage.tsx
- src/landing/components/ActionBox.tsx
- src/landing/components/GeneralStats.tsx
- src/landing/components/NoApplicationsPage.tsx
- src/styles/App.scss
- src/styles/app-list.scss
- src/styles/landing-page.scss
Our patternfly version was outdated and many properties have changed
> Pf lib update

- src/application/ApplicationDetail/ApplicationDetail.tsx
https://issues.jboss.org/browse/AEROGEAR-10274
Added the 'no variants' detail page
1. Run the new admin ui
2. Create a new application
3. Click on the newly created application to see its details
4. It should show the 'no variants' page
> feat(variant): added No Variants page

- package-lock.json
- package.json
- src/application/ApplicationDetail/ApplicationDetail.tsx
- src/application/ApplicationDetail/panels/CodeSnippet.tsx
- src/application/ApplicationDetail/panels/NoVariantsPanel.tsx
- src/application/ApplicationDetail/panels/VariantDetails.tsx
- src/application/ApplicationDetail/panels/VariantItem.tsx
- src/application/ApplicationDetail/panels/VariantsPanel.tsx
- src/application/ApplicationDetail/panels/android/AndroidCodeSnippets.tsx
- src/application/ApplicationDetail/panels/android/AndroidVariantDetails.tsx
- src/application/ApplicationDetail/panels/dialogs/EditAndroidNetworkOptions.tsx
- src/application/ApplicationDetail/panels/dialogs/RenewVariantSecret.tsx
- src/application/ApplicationDetail/snippets/cordova.tsx
- src/application/ApplicationDetail/snippets/index.ts
- src/application/ApplicationDetail/snippets/ios.tsx
- src/application/ApplicationDetail/snippets/java.tsx
- src/application/ApplicationDetail/snippets/push-config-android.ts
- src/application/ApplicationDetail/snippets/react-native-android.tsx
- src/application/ApplicationDetail/snippets/react-native-ios.tsx
- src/application/ApplicationList/ApplicationList.tsx
- src/application/ApplicationList/ApplicationListItem.tsx
- src/common/Label.tsx
- src/landing/components/GeneralStats.tsx
- src/styles/App.scss
- src/styles/app-details.scss
- src/styles/app-list.scss
- src/utils/UpsClientFactory.ts
https://issues.jboss.org/browse/AEROGEAR-10205
Added variant detail page for Android
The token count is currently hardcoded. Will be fixed in a future PR.
> feat(variant): added Android variant detail page

- .gitignore
- package-lock.json
- package.json
- src/App.tsx
- src/application/ApplicationDetail/panels/VariantsPanel.tsx
- src/application/ApplicationDetail/panels/dialogs/EditAndroidNetworkOptions.tsx
- src/application/ApplicationDetail/panels/dialogs/RenewVariantSecret.tsx
- src/application/crud/CreateApplicationPage.tsx
- src/application/crud/DeleteApplicationPage.tsx
- src/application/crud/UpdateApplicationPage.tsx
- src/landing/components/GeneralStats.tsx
- src/utils/UpsClientFactory.ts
The admin client library (used by the admin ui to speak with UPS) is being rewrote.
This PR updates the UI to those changes
**NOTE** The build now fails because the new admin client library has not been released yet
> refactor: refactored the code so that it works with the new admin client library

- src/application/ApplicationDetail/ApplicationDetail.tsx
- src/application/ApplicationDetail/panels/VariantDetails.tsx
- src/application/ApplicationDetail/panels/VariantsPanel.tsx
- src/application/ApplicationDetail/panels/ios_cert/EditIOSCertNetworkOptions.tsx
- src/application/ApplicationDetail/panels/ios_cert/iOSCertCodeSnippets.tsx
- src/application/ApplicationDetail/panels/ios_cert/iOSCertVariantDetails.tsx
https://issues.jboss.org/browse/AEROGEAR-10208
> feat(ios): implemented ios certificate variant details

- package-lock.json
- package.json
- src/App.tsx
- src/application/ApplicationDetail/panels/android/EditAndroidNetworkOptions.tsx
- src/context/Context.ts
When an error was happening on the server, no feedback was sent to the user
Added a new alert function to the application context provider
> feat(alerting): added ability to show alert toasts

- src/application/ApplicationDetail/ApplicationDetail.tsx
- src/application/ApplicationDetail/panels/CodeSnippet.tsx
- src/application/ApplicationDetail/panels/FormField.tsx
- src/application/ApplicationDetail/panels/VariantDetails.tsx
- src/application/ApplicationDetail/panels/VariantsPanel.tsx
- src/application/ApplicationDetail/panels/web_push/EditWebPushNetworkOptions.tsx
- src/application/ApplicationDetail/panels/web_push/WebPushCodeSnippets.tsx
- src/application/ApplicationDetail/panels/web_push/WebPushVariantDetails.tsx
- src/application/ApplicationDetail/snippets/index.ts
- src/application/ApplicationDetail/snippets/web_push/push-config.ts
https://issues.jboss.org/browse/AEROGEAR-10206
> feat(webpush): implemented webpush variant details

- src/application/ApplicationDetail/ApplicationDetail.tsx
- src/application/ApplicationDetail/panels/NoVariantsPanel.tsx
- src/application/VariantForms/VariantEditForm.tsx
- src/application/VariantForms/VariantSelectionForm.tsx
There was no `add variant` button in the app detail page
> Added add variant button

- package-lock.json
- package.json
- src/application/ApplicationList/ApplicationListItem.tsx
Application list was always showing 0 messages
Updated the patternfly version to overcome a bug
Fixed the application list page
> fix: 🐛 fixed messages count in application list

- package-lock.json
- package.json
- src/application/ApplicationDetail/ApplicationDetail.tsx
- src/application/ApplicationDetail/panels/ActivityLogPanel.tsx
- src/common/EllipsisText.tsx
- src/styles/App.scss
- src/styles/activity-list.scss
Requires https://github.com/aerogear/unifiedpush-admin-client/pull/114
> Activity log

- package-lock.json
- package.json
- src/application/ApplicationDetail/ApplicationDetail.tsx
- src/application/ApplicationDetail/panels/ActivityLogPanel.tsx
- src/application/ApplicationDetail/panels/android/AndroidVariantDetails.tsx
- src/application/ApplicationDetail/panels/dialogs/SendNotification.tsx
- src/common/UserTool.tsx
This adds a UI for sending push notifications
I've added a senderUI component and included the push sender library.
> Sender ui 

- package-lock.json
- package.json
- src/App.tsx
- src/application/ApplicationDetail/ApplicationDetail.tsx
- src/application/ApplicationDetail/InstallationsCount.tsx
- src/application/ApplicationDetail/SenderAPI.tsx
- src/application/ApplicationDetail/panels/ActivityLogPanel.tsx
- src/application/ApplicationDetail/panels/VariantDetails.tsx
- src/application/ApplicationDetail/panels/VariantItem.tsx
- src/application/ApplicationDetail/panels/android/AndroidVariantDetails.tsx
- src/application/ApplicationDetail/senderapi-snippets-panel/SenderApiSnippets.tsx
- src/application/VariantForms/VariantSelectionForm.tsx
- src/application/VariantForms/WebpushVariantForm.tsx
- src/application/crud/CreateVariantPage.tsx
- src/application/wizard/CreateApplicationWizard.tsx
- src/application/wizard/SendTestNotificationPage.tsx
- src/application/wizard/SetupPage.tsx
- src/application/wizard/SetupSenderAPI.tsx
- src/application/wizard/WizardFinalPage.tsx
- src/common/Header.tsx
- src/context/Context.ts
- src/utils/Alerts.ts
- src/utils/DocLinksUtils.ts
https://issues.jboss.org/browse/AEROGEAR-10183
> Aerogear 10183

- etc/nginx/conf.d/default.conf
https://issues.redhat.com/browse/INTLY-9766
Add HSTS Header
Update nginx configuration to set header
Build and deploy admin-ui, confirm strict hsts header is set.
> INTLY-9766 Set HSTS header
